%%{init: {'theme':'neutral'}}%%
graph BT

    %% projected development sub-units
    classDef DevUNIT fill:#78e4ff,stroke:#333,stroke-width:1px;
    %% external dependencies
    classDef EXTERN fill:red;
    %% input data
    classDef DATA fill:#1010EE33;

    subgraph Input
    MEG-Data
    T1-weighted_MRI
    T2-weighted_MRI
    end
    
    subgraph FreeSurfer Recon-all Pipeline
    T1-weighted_MRI --> preproc_and_skull_stripping
    T2-weighted_MRI --> preproc_and_skull_stripping
    preproc_and_skull_stripping --> voxel_segmentation
    voxel_segmentation --> mesh_reconstruction
    mesh_reconstruction --> head_model
    mesh_reconstruction --> registration_to_standard_space
    registration_to_standard_space --> apply_atlas
    apply_atlas --map back--> head_model
    head_model
    end
    
    
    subgraph Align using MNE
    MEG-Data --> 3D_Viewer
    head_model --> 3D_Viewer
    3D_Viewer --alignment--> Aligned_Data
    end
    
    subgraph SourceLoc
    Aligned_Data -->LF{{"LeadField (forward problem)"}}
    LF --inverse problem--> BF{{"BeamForming(DICS,LCMV)"}}
    BF-->FilterMatrix["Filter Matrix"]
    MEG-Data --Covariance/Coherence--> BF
    end


    class Viewer,HM,Segm,Atlas,MNE,BF,LF DevUNIT;
    class FreeSurfer,3D_Viewer EXTERN;
    class MEG-Data,T1-weighted_MRI,T2-weighted_MRI,Aligned_Data,FilterMatrix,head_model DATA;
